feat: add option to disable stats snapshots
nodeshift/opossum pull request #799
Opened 2023-07-29 20:17 UTC by gjethwani

Hello! I had a small feature request

Motivation

As I understand it, every bucket_interval (1s by default), opossum emits a snapshot of the stats in the Status class

this[SNAPSHOT_INTERVAL] = setInterval(_ => this.emit('snapshot', this.stats), bucketInterval);
My app doesn't actually listen to these stats and the extra call to setInterval clogs up the memory

Solution

Could we have a configurable option to disable the stats snapshots, thereby removing the extra call to setInterval?

Issue here: https://github.com/nodeshift/opossum/issues/798

2023-07-30 08:24 UTC, gjethwani commented
Corresponding PR in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66220

2023-07-31 14:41 UTC, lholmquist requested changes
This looks pretty good.  can you please add a test for this

2023-07-31 19:42 UTC, gjethwani commented
Thanks @lholmquist , just added some tests. Could you please give it a re-review?

2023-07-31 19:43 UTC, gjethwani commented
Also, would you like me to take care of the PR in DefinitelyTyped or is that something you would do when you release a new version?

2023-07-31 20:12 UTC, lance approved these changes
Looks good - thank you for the contribution!

2023-07-31 20:13 UTC, merged